site_name: Titor Technologies
site_url: https://titor.tech

docs_dir: docs

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Tags: tags.md
  - Projects: projects
  - Concepts: concepts
  - Analysis: analysis
  - Forecasts: forecasts

theme:
  name: material
  logo: img/titor.png

  palette:
    - scheme: slate
      primary: 'black'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: default
      primary: 'black'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra_css:
  - css/custom-styles.css

extra_javascript:
  - js/expand-nav.js

plugins:
  - search
  - blog
  - tags
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
        as_update: date
      categories:
        - categories
        - tags
      use_material_blog: true
      rss_feed_enabled: true
      json_feed_enabled: false
      use_git: false

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.superfences
